theme: jekyll-theme-cayman
title: Hitha Shri Nagaruru
description: AI Engineer & Master of Computer Science student at UC Irvine.
defaults:
  - scope:
      path: ""
    values:
      layout: default
